version: "3.8"

services:
  postgres:
    image: postgres:15.2-bullseye
    env_file:
      - ./.env
    restart: always
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    networks:
      comscore-planning-network:
        ipv4_address: 172.41.0.10
    ports:
      - "5432:5432"

  server:
    working_dir: /app
    env_file:
      - ./.env
    build:
      context: $PWD/server
      dockerfile: ./Dockerfile
      target: "prod"
    ports:
      - "3000:3000"
    networks:
      comscore-planning-network:
        ipv4_address: 172.41.0.13

  nginx:
    working_dir: /app
    env_file:
      - ./.env
    build:
      context: $PWD/frontend
      dockerfile: ./Dockerfile
      target: "prod"
    networks:
      comscore-planning-network:
        ipv4_address: 172.41.0.14
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres-data:

networks:
  comscore-planning-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.41.0.0/24
          gateway: 172.41.0.1
